### PR TITLE
expose repeat delay and interval parameters

### PR DESCRIPTION
**Pull request by chataign**
added parameters to allow using key repeats as per SDL documentation

### CODE REVIEW

**Comment by chataign** [comment]
Maybe the parameters should default to zero so that the node's default behaviour is to disable key repeat, as before.

**Comment by v01d** [comment]
Hi, thanks for the contribution. Yes, I'd rather the defaults to be as it was until now, if you don't mind adding that change.

I also prefer to initialize the node inside the constructor itself but I will change that later.

**Comment by chataign** [comment]
There you go, I updated the pull request so that key repeats are disabled by default

**Comment by v01d** [comment]
Thanks, but why is it necessary to add another parameter? Isn't it possible to use delay = 0 as a flag to disable repeating (as you do internally?)

**Comment by v01d** [comment]
Ah, I see that your intention is to provide the sane defaults for the repeat values if they are not specified. Ok, I'll merge as it is.

**Comment by chataign** [comment]
Yes exactly. Thanks!

**Pull request merged**
